fix(git): Fix the programs.git.signing option (#71)
I was getting this error building my hosts:

```
error: expected a set but found null: null
```

It took me a while to trace the issue but I finally figured out it's
coming from home-manager's `programs.git.signing` that defaulted to null
but it's no longer a submodule upstream instead it's expected to be an
attribute set.